version: '3.9'

services:
  
  medical-service:
    container_name: medical_service
    build: .
    ports:
      - "55555:55555"
    networks:
      - GLhost

networks:
  GLhost:
    external: true
    name: Global
    driver: bridge      

volumes:
  db:
  mongo-data:
